#https://github.com/terrakok/kmp-awesome

[versions]
ksp = "2.2.21-2.0.4"
auto-service-anno = "1.1.1"
squareup-poe = "2.2.0"

[libraries]
google-auto-service-anno = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service-anno" }
ksp-process-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-poe = { module = "com.squareup:kotlinpoet-ksp", version.ref = "squareup-poe" }


[bundles]