#https://github.com/terrakok/kmp-awesome

[versions]
gene-ksp-poe = "25.11.29"
gene-retrofit-ksp = "25.11.29"
gene-retrofit-ksp-anno = "25.11.29"

[libraries]
gene-ksp-poe = { module = "io.github.5gene:ksp-poe", version.ref = "gene-ksp-poe" }
gene-retrofit-ksp = { module = "io.github.5gene:retrofit-ksp", version.ref = "gene-retrofit-ksp" }
gene-retrofit-ksp-anno = { module = "io.github.5gene:retrofit-ksp-anno", version.ref = "gene-retrofit-ksp-anno" }

[bundles]

[plugins]

#需要手动配置 才可以使用
#dependencyResolutionManagement {
#    versionCatalogs {
#        create("wings") {
#            from(files("gradle/wings.versions.toml"))
#        }
#    }
#}